### ISSUE TITLE
Search results a tat dark

### ISSUE THREAD

**Issue by tdegeus** [jothepro/doxygen-awesome-css#15]
Still a huge fan! But to business:

I find the text of the search results a tat dark, and I've noticed straining my eyes a bit. What do you think?

<img width="455" alt="Screenshot 2021-04-21 at 19 50 32" src="https://user-images.githubusercontent.com/7030445/115598927-40955c80-a2db-11eb-9d58-5763f1debe68.png">

**Comment by jothepro** [comment]
Yep, totally agree. This is a huge problem that I was not able to address yet.

I would like to change a few things about the search results to improve readability:
- Increase font size
- choose same font that the rest of the site uses.
- choose text colors that are more readable in dark mode.

The problem is that the search result are loaded inside an iframe. Which means that the custom CSS has no control over it's formatting.

The only workaround that I could think of would be to choose a slightly lighter background color, so the readability of the content improves. 
The problem with a lighter background color: While the black text gets more readable, the blue text gets absolutely unidentifiable. To my eyes black on black is kind of readable if I look very closely, but blue on gray gets a blurry mess and I can hardly make out characters even on close inspection:
<img width="550" src="https://user-images.githubusercontent.com/21294002/115601837-8bfd3a00-a2de-11eb-931a-a35df06b5bea.png">

That's why I decided to go with the current solution of a relatively dark background. This is not optimal and I welcome every creative solution for that! :)

Maybe there is an easy way of injecting CSS into the search results that I haven't figured out yet?

**Comment by jothepro** [comment]
Hm I actually have a tip for you that might help a little bit:

The color of the search results (the blue portion of it, not the black) is predetermined by the doxygen color settings.
This is my setup, it already makes the blue a bit more vibrant and therefore readable:
```
HTML_COLORSTYLE_HUE    = 209
HTML_COLORSTYLE_SAT    = 255
HTML_COLORSTYLE_GAMMA  = 113
```

But you could also choose a different color to improve the contrast (Of course you don't want to choose bright yellow, that's just to show you the effect):
<img width="524" src="https://user-images.githubusercontent.com/21294002/115609653-1ac28480-a2e8-11eb-8f0d-0320b121ba90.png">
```
HTML_COLORSTYLE_HUE    = 50
HTML_COLORSTYLE_SAT    = 255
HTML_COLORSTYLE_GAMMA  = 255
```

Be aware that this has side effects on other ui elements as well (oops the color of the detail level should not be affected and the folder icons have a strange color, I guess that's a bug in my theme) and that it is not not dark mode specific, so the color should work for both dark and light mode.
<img width="589" src="https://user-images.githubusercontent.com/21294002/115609885-66752e00-a2e8-11eb-8ab4-42c08e3ab662.png">

**Comment by tdegeus** [comment]
Hi @jothepro . Thanks for your replies. Given the internal limitations I think that the current style is indeed perfectly acceptable. It seems like an issue that should be addressed upstream? In the long terms there seems to be willingness to integrate a dark theme in doxygen, ref https://github.com/doxygen/doxygen/issues/8404 , so maybe in the long term you could consider proposing this theme here to be integrated in doxygen . That would be the perfect opportunity to resolve these issues.

Thanks for the quick-fix. Seems quite ok as a work-around. Though I must admit things are not super urgent for me: I filed this issue because I wish the best for this awesome theme !
