### ISSUE TITLE
Treeview Layout - Lowest level fromating.

### ISSUE THREAD

**Issue by Darkblizzard21** [jothepro/doxygen-awesome-css#35]
Hi, 
i recently build dox for a plugin with this nice css. But i found following problem:

The lowest level of the tree view is always at the right border of the tree view. 

![doxygen](https://user-images.githubusercontent.com/76403378/125535486-7eb42d1f-ab0b-4c48-97ac-f6d7dd93a151.png)

I already fixed it for me locally by adding `display: inline-block;` to the .arrow section of the .css file. The the tree view looks as i expected:

![doxygenbetter](https://user-images.githubusercontent.com/76403378/125535619-53e07085-154b-400e-a02f-3179228ceb55.png)

I would make a pull request my self, but i don't have the right to do so.

Cheers - darkblizzard

**Comment by jothepro** [comment]
Given the fact that the problem doesn't seem to occur on the [demo page](https://jothepro.github.io/doxygen-awesome-css/), I am tempted to think that this may be a problem with your specific setup, or with an incompatible Doxygen configuration.
<img width="200" alt="Bildschirmfoto 2021-07-14 um 10 10 40" src="https://user-images.githubusercontent.com/21294002/125587244-0c46c6fe-e70d-41d2-9558-b46b2b99778a.png">

The second screenshot that you posted raises a question to me: Is "DatamodelFeedback" really a subsection of "Datamodel Class Hierarchy"? Because the arrow in the blue rectangle indicates to me that the "Datamodel Class Hierarchy" tree is closed (►), which means it's children should not be visible. 🤔 

Can you pls provide the following information about your setup?
- Doxygen version
- Doxygen Awesome CSS version
- if possible, the Doxyfile you are using to generate the docs
- if possible, a link to the repository or the generated docs, so I can inspect the problem myself.


> I would make a pull request my self, but i don't have the right to do so.

You should be able to create a PR, if not I'll have to fix the repository configuration. :/
Can you describe what you tried to open a PR, or what gh is telling you why you're not allowed to do so? 🤔

**Comment by Darkblizzard21** [comment]
Yes it happened to all leafs in my documentation.

The structure of the "Module: Balanceable Variables DataModel" page is the following:
```
@section datamodelLayers Datamodel Class Hierarchy

@subsection datamodelLayerOne IIDataModel

@subsection datamodelLayerTwo FDataModel

@subsection datamodelLayerThree FDataModelBackendLinked

@section datamodelFeedback DatamodelFeedback

@section datamodeloverviewvisual Complete Visual-Overview 
```
So my fix is not 100% clean, because the section with subsections is still on a different level than those without subsections.

My setup:

- Doxygen version: 1.9.1 
- Doxygen Awesome CSS version: 1.5.1 (cloned at 12.07.21)
- Browser version: checked with FireFox 89.0.2 and 90.0
- if possible, the Doxyfile you are using to generate the docs: doxyfile (datapaths shorted) [BalancingHubDoxyfile.txt](https://github.com/jothepro/doxygen-awesome-css/files/6816251/BalancingHubDoxyfile.txt)
- if possible, a link to the repository or the generated docs, so I can inspect the problem myself: the project currently is saved on the gitlab of my university. So im unfortunately not able make the repository public at the moment.

**Comment by dmadison** [comment]
Hi there. I was just testing this on a private repo and ran into the same problem. It turns out I accidentally placed the CSS link in the `HTML_STYLESHEET` field instead of the `HTML_EXTRA_STYLESHEET` field. I just downloaded your Doxyfile and it looks like you made the same mistake.
