### ISSUE TITLE
Default page width

### ISSUE THREAD

**Issue by leomccormack** [jothepro/doxygen-awesome-css#36]
This is not really an "issue". 
Actually I mainly just want to thank the contributors to this project, since I had been looking around for a modern doxygen theme with light/dark modes for quite a while now - to no avail.
This one ticked pretty much all the boxes for one of our projects (https://leomccormack.github.io/Spatial_Audio_Framework/). 

The only problem I had was with the default maxwidth, which looks comically narrow on a 1440p/4K monitor. 
`--content-maxwidth: 900px;`
Perhaps setting this to "auto", or at least increasing this value, would be better for a default configuration?

In any case, great work, and thanks again!

**Comment by jpgarza93** [comment]
I also had a problem with the --content-maxwidth, but it was easy to override the value. All I did was add this un my custom.css file:

/*--- OVERRIDE VARIABLES ---*/
html {
    --content-maxwidth: 1180px !important;
}

For example, see my docs [here](https://rapidcode.roboticsys.com/index.html).

Hope this helps.

**Comment by jothepro** [comment]
Thanks for your feedback!
I've increased the default width to `1000px` in https://github.com/jothepro/doxygen-awesome-css/commit/8868faceb998cea5d500142093857fb50a9ad8e4 because it seems multiple users think `900px` is too small. As @jpgarza93 mentioned you can and should choose your own preferred content width by overriding `--content-maxwidth`.
