### ISSUE TITLE
Project name cropped in sidebar instead of newline

### ISSUE THREAD

**Issue by mwiesenberger** [jothepro/doxygen-awesome-css#76]
Hi, 

I just tried to upgrade from 1.6.1 to 2.0.3. It looks good overall but I found one issue. The sidebar title is cropped as seen here
![new](https://user-images.githubusercontent.com/5844863/173324723-9f760633-943a-4407-945e-4215689491d0.png)
Before it was like this:
![old](https://user-images.githubusercontent.com/5844863/173324745-78ee7e53-23ac-49de-8129-ddfd92f6c6cd.png)

The old code is here
https://github.com/feltor-dev/feltor/tree/master/doc

What I did was to replace the two doxygen-awesome files and the header.html with the updated versions.
I am guessing it is something small to fix, but I just don't know where to look or if it is actually something I did wrong somehow
Thanks
Matthias

**Comment by jothepro** [comment]
This line disables the line-wrap: https://github.com/jothepro/doxygen-awesome-css/blob/main/doxygen-awesome-sidebar-only.css#L41

I've introduced this as a safety measure so no unexpected line break happens due to a few pixels being missing because of a different font or browser.

You can restore the old behavior like this:

```css
#projectname {
     white-space: normal;
 }
```

**Comment by mwiesenberger** [comment]
cool, thanks, that worked
